#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
AIRR-ML-25 Dataset 3

Candidate clone list:
  TSV with columns: cdr3, v_gene
Generated by default as intersection between train and test clone sets (overlapping_with_test).

Output prediction format:
  ID, dataset, label_positive_probability

"""

import os
import json
import pickle
import argparse
from dataclasses import dataclass, asdict
from typing import Dict, Tuple, List, Set, Optional
from collections import defaultdict

import numpy as np
import pandas as pd
from tqdm import tqdm
from sklearn.linear_model import LogisticRegression


# -------------------------
# Utils
# -------------------------

def ensure_dir(p: str):
    if p and not os.path.exists(p):
        os.makedirs(p, exist_ok=True)

def save_pickle(obj, path: str):
    ensure_dir(os.path.dirname(path))
    with open(path, "wb") as f:
        pickle.dump(obj, f)

def load_pickle(path: str):
    with open(path, "rb") as f:
        return pickle.load(f)

def to_bool(x) -> bool:
    if isinstance(x, bool):
        return x
    if isinstance(x, (int, np.integer)):
        return bool(x)
    s = str(x).strip().lower()
    if s in ("true", "t", "1", "yes", "y"):
        return True
    if s in ("false", "f", "0", "no", "n"):
        return False
    raise ValueError(f"Cannot parse bool from {x}")

def detect_col(df: pd.DataFrame, candidates: List[str], what: str) -> str:
    for c in candidates:
        if c in df.columns:
            return c
    raise ValueError(f"Cannot find {what} column. candidates={candidates}, got={list(df.columns)}")

CDR3_COL_CANDIDATES  = ["junction_aa", "cdr3aa", "cdr3", "CDR3b", "CDR3"]
VGENE_COL_CANDIDATES = ["v_call", "v_gene", "TRBV", "v"]

def norm_v_gene(v: str, v_gene_trans: Dict[str, str], keep_na: bool = True) -> str:
    if pd.isna(v):
        return "na" if keep_na else ""
    v = str(v)
    return v_gene_trans.get(v, v)

def resolve_tsv_path(tsv_dir: str, sample_id: str, filename: str) -> str:
    # primary: filename in metadata
    p = os.path.join(tsv_dir, filename)
    if os.path.isfile(p):
        return p
    # fallback: sample_id.tsv
    alt = os.path.join(tsv_dir, f"{sample_id}.tsv")
    if os.path.isfile(alt):
        return alt
    raise FileNotFoundError(f"TSV not found: {p} (or {alt})")

def read_sample_tsv(tsv_path: str, v_gene_trans: Dict[str, str]) -> pd.DataFrame:
    df = pd.read_csv(tsv_path, sep="\t")
    ccol = detect_col(df, CDR3_COL_CANDIDATES, "CDR3")
    vcol = detect_col(df, VGENE_COL_CANDIDATES, "V gene")

    sub = df[[ccol, vcol]].dropna().copy()
    sub.columns = ["cdr3", "v_gene"]
    sub["cdr3"] = sub["cdr3"].astype(str)
    sub["v_gene"] = sub["v_gene"].apply(lambda x: norm_v_gene(x, v_gene_trans=v_gene_trans))
    # unique within sample (presence/absence)
    sub = sub.drop_duplicates()
    return sub

def load_metadata(meta_csv: str, require_label: bool) -> pd.DataFrame:
    meta = pd.read_csv(meta_csv)
    required = {"repertoire_id", "filename"}
    missing = required - set(meta.columns)
    if missing:
        raise ValueError(f"metadata missing columns {missing}, got={list(meta.columns)}")
    if require_label and "label_positive" not in meta.columns:
        raise ValueError("Training metadata must include 'label_positive' column.")

    meta = meta.copy()
    meta["sample_id"] = meta["repertoire_id"].astype(str)
    if "label_positive" in meta.columns:
        meta["label_positive"] = meta["label_positive"].apply(to_bool)
    return meta


# -------------------------
# Candidate generation
# -------------------------

def load_clone_set_from_metadata(meta: pd.DataFrame, tsv_dir: str, v_gene_trans: Dict[str, str]) -> Set[Tuple[str, str]]:
    out: Set[Tuple[str, str]] = set()
    for row in tqdm(meta.itertuples(index=False), total=len(meta), desc="Scan samples"):
        sid = str(row.sample_id)
        fn = str(row.filename)
        tsv_path = resolve_tsv_path(tsv_dir, sid, fn)
        df = read_sample_tsv(tsv_path, v_gene_trans=v_gene_trans)
        out.update(zip(df["cdr3"].values, df["v_gene"].values))
    return out

def cmd_make_candidates(args):
    v_gene_trans = load_pickle(args.v_gene_trans_pkl) if args.v_gene_trans_pkl else {}

    train_meta = load_metadata(args.train_meta, require_label=False)
    test_meta  = load_metadata(args.test_meta, require_label=False)

    S_train = load_clone_set_from_metadata(train_meta, args.train_dir, v_gene_trans)
    S_test  = load_clone_set_from_metadata(test_meta,  args.test_dir,  v_gene_trans)

    if args.mode == "intersect":
        cand = S_train.intersection(S_test)
    else:
        cand = S_train.union(S_test)

    out = pd.DataFrame(list(cand), columns=["cdr3", "v_gene"]).sort_values(["v_gene", "cdr3"])
    ensure_dir(os.path.dirname(args.out_tsv) or ".")
    out.to_csv(args.out_tsv, sep="\t", index=False)

    print(f"[ok] train unique clones: {len(S_train)}")
    print(f"[ok] test  unique clones: {len(S_test)}")
    print(f"[ok] candidate clones  : {len(cand)} (mode={args.mode})")
    print(f"[ok] wrote: {args.out_tsv}")


# -------------------------
# Enrichment / OR
# -------------------------

def compute_or(a: int, b: int, c: int, d: int, pseudo: float = 0.5) -> float:
    # OR = (a*d)/(b*c), add pseudo to avoid zero
    return (a + pseudo) * (d + pseudo) / ((b + pseudo) * (c + pseudo))

def build_clone_to_samples(
    meta: pd.DataFrame,
    tsv_dir: str,
    v_gene_trans: Dict[str, str],
    label_value: bool,
) -> Dict[Tuple[str, str], Set[str]]:
    out = defaultdict(set)
    sub_meta = meta[meta["label_positive"] == label_value].copy()
    it = tqdm(sub_meta.itertuples(index=False), total=len(sub_meta), desc=f"Scan {'POS' if label_value else 'NEG'}")
    for row in it:
        sid = str(row.sample_id)
        fn = str(row.filename)
        tsv_path = resolve_tsv_path(tsv_dir, sid, fn)
        df = read_sample_tsv(tsv_path, v_gene_trans=v_gene_trans)
        for c, v in zip(df["cdr3"].values, df["v_gene"].values):
            out[(c, v)].add(sid)
    return out

def load_candidates(candidate_tcr_tsv: str, v_gene_trans: Dict[str, str]) -> List[Tuple[str, str]]:
    df = pd.read_csv(candidate_tcr_tsv, sep="\t")
    if not {"cdr3", "v_gene"}.issubset(df.columns):
        raise ValueError(f"Candidate file must contain columns cdr3,v_gene. Got={list(df.columns)}")
    df["cdr3"] = df["cdr3"].astype(str)
    df["v_gene"] = df["v_gene"].apply(lambda x: norm_v_gene(x, v_gene_trans=v_gene_trans))
    return list(zip(df["cdr3"].values, df["v_gene"].values))

def select_strong_clones(
    candidates: List[Tuple[str, str]],
    clone2pos: Dict[Tuple[str, str], Set[str]],
    clone2neg: Dict[Tuple[str, str], Set[str]],
    n_pos_total: int,
    n_neg_total: int,
    min_pos_samples: int,
    or_thresh: float,
) -> pd.DataFrame:
    rows = []
    for clone in tqdm(candidates, desc="Compute OR"):
        pos_set = clone2pos.get(clone, set())
        neg_set = clone2neg.get(clone, set())

        a = len(pos_set)              # pos with clone
        c = len(neg_set)              # neg with clone
        b = n_pos_total - a           # pos without
        d = n_neg_total - c           # neg without
        OR = compute_or(a, b, c, d)

        rows.append((clone[0], clone[1], a, c, OR))

    df = pd.DataFrame(rows, columns=["cdr3", "v_gene", "n_pos_samples", "n_neg_samples", "OR"])
    df_strong = df[(df["n_pos_samples"] >= min_pos_samples) & (df["OR"] >= or_thresh)].copy()
    df_strong = df_strong.sort_values(["OR", "n_pos_samples"], ascending=False).reset_index(drop=True)
    return df_strong


# -------------------------
# Feature matrix
# -------------------------

def build_feature_matrix(
    sample_ids: List[str],
    filenames: List[str],
    tsv_dir: str,
    strong_clones: List[Tuple[str, str]],
    v_gene_trans: Dict[str, str],
) -> np.ndarray:
    clone_index = {cl: j for j, cl in enumerate(strong_clones)}
    X = np.zeros((len(sample_ids), len(strong_clones)), dtype=np.int8)

    for i, (sid, fn) in enumerate(tqdm(list(zip(sample_ids, filenames)), desc="Build X")):
        tsv_path = resolve_tsv_path(tsv_dir, sid, fn)
        df = read_sample_tsv(tsv_path, v_gene_trans=v_gene_trans)
        for c, v in zip(df["cdr3"].values, df["v_gene"].values):
            j = clone_index.get((c, v), None)
            if j is not None:
                X[i, j] = 1
    return X


# -------------------------
# Bundle
# -------------------------

@dataclass
class PublicTCRBundle:
    strong_clones: List[Tuple[str, str]]
    min_pos_samples: int
    or_thresh: float
    model: object
    meta: Dict

    def to_meta_dict(self):
        d = asdict(self)
        d["model"] = None
        return d


# -------------------------
# Commands: train / predict
# -------------------------

def cmd_train(args):
    v_gene_trans = load_pickle(args.v_gene_trans_pkl) if args.v_gene_trans_pkl else {}

    meta = load_metadata(args.train_meta, require_label=True)

    pos_ids = meta.loc[meta["label_positive"] == True, "sample_id"].astype(str).tolist()
    neg_ids = meta.loc[meta["label_positive"] == False, "sample_id"].astype(str).tolist()
    print(f"[info] Train samples: pos={len(pos_ids)} neg={len(neg_ids)}")

    clone2pos = build_clone_to_samples(meta, args.train_dir, v_gene_trans, True)
    clone2neg = build_clone_to_samples(meta, args.train_dir, v_gene_trans, False)

    candidates = load_candidates(args.candidate_tcr_tsv, v_gene_trans=v_gene_trans)
    print(f"[info] Candidate clones: {len(candidates)}")

    df_strong = select_strong_clones(
        candidates=candidates,
        clone2pos=clone2pos,
        clone2neg=clone2neg,
        n_pos_total=len(pos_ids),
        n_neg_total=len(neg_ids),
        min_pos_samples=args.min_pos_samples,
        or_thresh=args.or_thresh,
    )
    strong_clones = list(zip(df_strong["cdr3"].values.tolist(), df_strong["v_gene"].values.tolist()))
    print(f"[info] Strong clones selected: {len(strong_clones)}")
    if len(strong_clones) == 0:
        raise RuntimeError("No strong clones selected. Lower thresholds or change candidate set.")

    # train matrix
    train_samples = meta["sample_id"].astype(str).tolist()
    train_files   = meta["filename"].astype(str).tolist()
    y = meta["label_positive"].astype(int).to_numpy()

    X = build_feature_matrix(train_samples, train_files, args.train_dir, strong_clones, v_gene_trans)

    model = LogisticRegression(max_iter=args.max_iter, class_weight="balanced", random_state=args.seed)
    model.fit(X, y)

    bundle = PublicTCRBundle(
        strong_clones=strong_clones,
        min_pos_samples=args.min_pos_samples,
        or_thresh=args.or_thresh,
        model=model,
        meta={
            "n_pos": len(pos_ids),
            "n_neg": len(neg_ids),
            "n_candidates": len(candidates),
            "n_strong": len(strong_clones),
            "args": vars(args),
        },
    )

    ensure_dir(args.out_dir)
    out_pkl = os.path.join(args.out_dir, "dataset3_publictcr_bundle.pkl")
    out_json = os.path.join(args.out_dir, "dataset3_publictcr_bundle_meta.json")
    out_strong = os.path.join(args.out_dir, "strong_clones.tsv")

    save_pickle(bundle, out_pkl)
    with open(out_json, "w") as f:
        json.dump(bundle.to_meta_dict(), f, indent=2)
    df_strong.to_csv(out_strong, sep="\t", index=False)

    print(f"[ok] Saved bundle: {out_pkl}")
    print(f"[ok] Saved meta  : {out_json}")
    print(f"[ok] Saved strong clones table: {out_strong}")

def cmd_predict(args):
    v_gene_trans = load_pickle(args.v_gene_trans_pkl) if args.v_gene_trans_pkl else {}

    bundle: PublicTCRBundle = load_pickle(args.model_bundle_pkl)
    model = bundle.model
    strong_clones = bundle.strong_clones

    if args.test_meta:
        meta = load_metadata(args.test_meta, require_label=False)
        sample_ids = meta["sample_id"].astype(str).tolist()
        filenames  = meta["filename"].astype(str).tolist()
    else:
        files = sorted([f for f in os.listdir(args.test_dir) if f.endswith(".tsv")])
        sample_ids = [os.path.splitext(f)[0] for f in files]
        filenames  = files

    X = build_feature_matrix(sample_ids, filenames, args.test_dir, strong_clones, v_gene_trans)
    prob = model.predict_proba(X)[:, 1]

    out = pd.DataFrame({
        "ID": sample_ids,
        "dataset": args.dataset_name,
        "label_positive_probability": prob.astype(float),
    })
    ensure_dir(os.path.dirname(args.out_csv) or ".")
    out.to_csv(args.out_csv, index=False)
    print(f"[ok] Wrote predictions: {args.out_csv} (n={len(out)})")


# -------------------------
# CLI
# -------------------------

def build_parser():
    p = argparse.ArgumentParser("airrml25_dataset3_publictcr_allinone.py")
    sub = p.add_subparsers(dest="cmd", required=True)

    # make-candidates
    mc = sub.add_parser("make-candidates")
    mc.add_argument("--train_meta", required=True)
    mc.add_argument("--train_dir", required=True)
    mc.add_argument("--test_meta", required=True)
    mc.add_argument("--test_dir", required=True)
    mc.add_argument("--out_tsv", required=True)
    mc.add_argument("--mode", choices=["intersect", "union"], default="intersect")
    mc.add_argument("--v_gene_trans_pkl", default=None)
    mc.set_defaults(func=cmd_make_candidates)

    # train
    tr = sub.add_parser("train")
    tr.add_argument("--train_meta", required=True)
    tr.add_argument("--train_dir", required=True)
    tr.add_argument("--candidate_tcr_tsv", required=True)
    tr.add_argument("--out_dir", required=True)

    tr.add_argument("--min_pos_samples", type=int, default=5)
    tr.add_argument("--or_thresh", type=float, default=9.0)

    tr.add_argument("--max_iter", type=int, default=3000)
    tr.add_argument("--seed", type=int, default=0)

    tr.add_argument("--v_gene_trans_pkl", default=None)
    tr.set_defaults(func=cmd_train)

    # predict
    pr = sub.add_parser("predict")
    pr.add_argument("--model_bundle_pkl", required=True)
    pr.add_argument("--test_dir", required=True)
    pr.add_argument("--dataset_name", required=True)
    pr.add_argument("--out_csv", required=True)
    pr.add_argument("--test_meta", default=None)
    pr.add_argument("--v_gene_trans_pkl", default=None)
    pr.set_defaults(func=cmd_predict)

    return p

def main():
    args = build_parser().parse_args()
    args.func(args)

if __name__ == "__main__":
    main()
